<?php

namespace ProfilingBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecent1()
    {
        $q=$this->getEntityManager()->createQuery("select v from ProfilingBundle:Post v  where 
              v.datePublication < CURRENT_TIME () ORDER BY v.datePublication DESC  ")->setMaxResults(3);
        return $q->getResult();
    }
    public function findLatest(){
        return $this->latestQuery()->getQuery();
    }
    public function findByTag($nom)
    {
            return $this->latestQuery()
            ->join('p.tag', 't')
            ->where('t.nom = :nom')
            ->setParameter('nom', $nom)
                ->getQuery();
    }
    public function latestQuery(){
        return $this->createQueryBuilder('p')
            ->select('p');
    }
}
