<?php

namespace ProfilingBundle\Repository;

/**
 * SkillstabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillstabRepository extends \Doctrine\ORM\EntityRepository
{
}
