<?php

namespace ProfilingBundle\Controller;

use ProfilingBundle\Entity\Album;
use ProfilingBundle\Entity\Post;
use ProfilingBundle\Form\PostType;
use ProfilingBundle\Repository\PostRepository;
use SebastianBergmann\CodeCoverage\Node\File;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\DateTime;
use UserBundle\Entity\User;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ProfileController extends Controller
{
public function index_profileAction()
{
    $u = $this->container->get('security.token_storage')->getToken()->getUser();
    $em=$this->getDoctrine()->getManager();
    $categories = $em->getRepository('EventBundle:category')->findAll();
    return $this->render('@Profiling/Profile.html.twig',array(
        'curr_user'=>$u ,'categories'=>$categories,
    ));
}
    public function albumAction(Request $request)
    {
        $u=$this->container->get('security.token_storage')->getToken()->getUser();
        $em = $this->getDoctrine()->getManager();
        $album = new Album();
        $categories = $em->getRepository('EventBundle:category')->findAll();
        //----------------
        $form=$this->createFormBuilder($album)
            ->add('imageFile', VichImageType::class)
            ->add('user',HiddenType::class, array('data' => $u))
            ->add('Ajouter',SubmitType::class)
            ->getForm();
        $form->handleRequest($request);
        if (($form->isSubmitted())&&($form->isValid()))
        {
            $album=$form->getData();
            $album->setUser($u);
            $taw=new \DateTime('now');
            $album->setDatePublication($taw);
            $em->persist($album);
            $em->flush();
            return $this->redirectToRoute('album');
        }
        //-------------------supprimer photo
        /*if ($request->isMethod('POST')) {
            if ($request->request->has('idp')) {
                $p= $em->getRepository(Album::class)->find($request->get("idp"));
                $em->remove($p);
                $em->flush();
                return $this->redirectToRoute("album");
            }
            return $this->redirectToRoute('album');
        }*/
        //----------------------------------

        $photos=$em->getRepository(Album::class)->findBy(array('user' => $u->getId()),array('datePublication' => 'ASC'));

        return $this->render('@Profiling/ProfileSettings.html.twig',array(
            'curr_user'=>$u,'form'=>$form->createView(),'photos'=>$photos,'categories'=>$categories,
        ));
    }

    public function createAction(Request $request)
    {
        $u=$this->container->get('security.token_storage')->getToken()->getUser();
        $id=$u->getId();
        $post = new Post();
        $post->setUser($this->getUser());
        $form=$this->createForm(PostType::class,$post);
        $form->handleRequest($request);
        if($form->isValid())
        {
            $em=$this->getDoctrine()->getManager();
            $post->setDatePublication(new \DateTime('now '));

            $file = $post->getImage();
            if($file != ""){
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('image_directory',$fileName),
                $fileName
            );
            $post->setImage($fileName);
            $post= $form->getData();
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute("showPost");}else{
                $em=$this->getDoctrine()->getManager();
                $post->setDatePublication(new \DateTime('now '));
                $post->setImage("");
                $post= $form->getData();
                $em->persist($post);
                $em->flush();
                return $this->redirectToRoute("showPost");
            }
        }
        return $this->render('@Profiling/post.html.twig', array(
            "form"=>$form->createView()
        ));
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Post::class,
        ));

    }
    public function readAction(Request $request)
    {

        $u=$this->container->get('security.token_storage')->getToken()->getUser();
        $em= $this->getDoctrine()->getManager();


        if($tag = $request->query->get('tag')){
            $recent=$em->getRepository(Post::class)->findByTag($tag)->getResult();
        }
        else
        {
            $recent= $em->getRepository(Post::class)->findBy(array('user' => $u),array('datePublication' => 'DESC'));
            return $this->render("@Profiling/showPost.html.twig",array("recent"=>$recent));
        }

        return $this->render('@Profiling/showPost.html.twig', array(
            "recent"=>$recent,"curr_user"=>$u
        ));
    }
    public function updateAction(Request $request,$idp)
    {
        $em= $this->getDoctrine()->getManager();
        $post=$em->getRepository(Post::class)->find($idp);
        $form=$this->createForm(PostType::class,$post);
        $form->handleRequest($request);
        if($form->isSubmitted())
        {
            $em=$this->getDoctrine()->getManager();
            $file = $post->getImage();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('image_directory',$fileName),
                $fileName
            );

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $post->setImage($fileName);
            $post->setDatePublication(new \DateTime('now '));
            $post=$form->getData();
            $em->persist($post);
            $em->flush();
            return $this->redirectToRoute("showPost");
        }
        return $this->render('@Profiling/postupdate.html.twig', array(
            "form"=>$form->createView()

        ));


    }
    public function paramInfoAction(Request $request){
        $u= $this->container->get('security.token_storage')->getToken()->getUser();
        $em = $this->getDoctrine()->getManager();
        //----------------
        $form=$this->createFormBuilder($u)
            ->add('Add',SubmitType::class)
            ->getForm();
        $form->handleRequest($request);
        if (($form->isSubmitted())&&($form->isValid()))
        {
            $u=$form->getData();
            $em->flush();
            return $this->redirectToRoute('paramInfo');
        }
        //----------------
        $user = $em->getRepository(User::class)->find($u->getId());
        if ($request->isMethod('POST')) {
            $user->setNom($request->get('nom'));
            $user->setPrenom($request->get('prenom'));
            $user->setgender($request->get('gender'));
            $user->setadresse($request->get('adresse'));
            $user->setPhoneNumber($request->get('phoneNumber'));
            $user->setApropos($request->get('apropos'));
            $user->setOccupation($request->get('occupation'));
                $em->persist($user);
                $em->flush();
                return $this->redirectToRoute('paramInfo');
            }



        return $this->render('@Profiling/paraminfo.html.twig', array(
            'us' => $u,'form'=>$form->createView()
        ));
    }
    public function autreprofileAction($id){
        $em = $this->getDoctrine()->getManager();
        $u = $em->getRepository(User::class)->findBy(array('id' => $id));
        $photos=$em->getRepository(Album::class)->findBy(array('user'=>$id),null,9,null);
        $posts=$em->getRepository(Post::class)->findBy(array('user'=>$id),array('datePublication'=>'DESC'));

        return $this->render('@Profiling/autreprofile.html.twig',array(
           'autreuser'=>$u[0],'photos'=>$photos,'posts'=>$posts
        ));
    }

}