<?php

namespace ForumBundle\Repository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecent1()
    {
        $q=$this->getEntityManager()->createQuery("select t from ForumBundle:Topic t  where 
              t.datePubliee < CURRENT_TIME () ORDER BY t.datePubliee DESC");
        return $q->getResult();
    }
    public function findtopic($id){
        $q=$this->getEntityManager()
            ->createQuery("select t from ForumBundle:Topic t WHERE t.id=:id ")
            ->setParameter(":id",$id);
        return $q->getResult();
    }
}
